CREATE DATABASE ACME_DB;
CREATE TABLE PERSONA(
  ID_PERSONA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOMBRES VARCHAR(50) NOT NULL ,
  APELLIDOS VARCHAR(50) NOT NULL ,
  FECHA_NACIMIENTO DATE NOT NULL ,
);
CREATE TABLE ROL(
  ID_ROL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DESCRIPCION VARCHAR(50) NOT NULL
)
CREATE TABLE USUARIO(
  ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_PERSONA INT NOT NULL ,
  CORREO VARCHAR(50) NOT NULL ,
  PASSWORD VARCHAR(50) NOT NULL ,
  FECHA_CREACION DATETIME,
  ID_ROL INT,

 FOREIGN KEY (ID_ROL)
    REFERENCES ROL(ID_ROL),

  FOREIGN KEY (ID_PERSONA)
    REFERENCES Persona(ID_PERSONA)
);
CREATE TABLE CLIENTE(
  ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOMBRES VARCHAR(50) NOT NULL ,
  APELLIDOS VARCHAR(50) NOT NULL ,
  DIRECCION VARCHAR(50) NOT NULL ,
  NIT VARCHAR(15) NOT NULL
);
CREATE TABLE BODEGA(
  ID_BODEGA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DESCRIPCION VARCHAR(50) NOT NULL,
  UBICACION VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUCTO(
  ID_PRODUCTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(50) NOT NULL
);
CREATE TABLE PRECIO(
  ID_PRECIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_PRODUCTO INT NOT NULL ,
  PRECIO DECIMAL NOT NULL ,

  FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(ID_PRODUCTO)
);
CREATE TABLE INVENTARIO(
  ID_INVENTARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_PRODUCTO INT NOT NULL ,
  ID_BODEGA INT NOT NULL ,
  EXISTENCIA INT NOT NULL ,
  FECHA_ACTUALIZACION DATETIME NOT NULL ,

  FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(ID_PRODUCTO),

  FOREIGN KEY (ID_BODEGA)
   REFERENCES BODEGA(ID_BODEGA)
);
CREATE TABLE BOLETA_ENTRADA(
  ID_BOLETA_ENTRADA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DESCRIPCION VARCHAR(50) NOT NULL,
  CANTIDAD INT NOT NULL ,
  ID_PRODUCTO INT NOT NULL ,
  ID_BODEGA INT NOT NULL ,

    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(ID_PRODUCTO),

  FOREIGN KEY (ID_BODEGA)
   REFERENCES BODEGA(ID_BODEGA)
);
CREATE TABLE FACTURA(
  ID_FACTURA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NUM_FACTURA INT NOT NULL ,
  NUM_SERIE VARCHAR(50)  ,
  FECHA DATE NOT NULL ,
  ID_CLIENTE INT NOT NULL ,
  ID_BODEGA INT NOT NULL ,
  ID_USUARIO INT NOT NULL ,

  FOREIGN KEY (ID_CLIENTE)
  REFERENCES CLIENTE(ID_CLIENTE),

  FOREIGN KEY (ID_USUARIO)
  REFERENCES USUARIO(ID_USUARIO),

  FOREIGN KEY (ID_BODEGA)
  REFERENCES BODEGA(ID_BODEGA)
);
CREATE TABLE FACTURA_DETALLE(
  ID_FACTURA_DETALLE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_FACTURA INT NOT NULL ,
  ID_PRODUCTO INT NOT NULL ,
  CANTIDAD INT NOT NULL ,
  PRECIO DECIMAL NOT NULL ,

  FOREIGN KEY (ID_FACTURA)
    REFERENCES FACTURA(ID_FACTURA),

     FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(ID_PRODUCTO)
);